# Part I: Data Preparation

## Read data from csv

In [7]:
import os
import pandas as pd

DATA_DIR = 'data'
CSV_FILE = DATA_DIR + '/KaggleV2-May-2016.csv'

# read data using read_csv function
def read_csv(data_dir=DATA_DIR, csv_file=CSV_FILE):
    if not os.path.isdir(data_dir):
        os.makedirs(data_dir)
    return pd.read_csv(CSV_FILE)

appt_df = read_csv()
appt_df

,PatientId,AppointmentID,Gender,ScheduledDay,AppointmentDay,Age,Neighbourhood,Scholarship,Hipertension,Diabetes,Alcoholism,Handcap,SMS_received,No-show
0,2.987250e+13,5642903,F,2016-04-29T18:38:08Z,2016-04-29T00:00:00Z,62,JARDIM DA PENHA,0,1,0,0,0,0,No
1,5.589978e+14,5642503,M,2016-04-29T16:08:27Z,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,0,0,0,0,0,No
2,4.262962e+12,5642549,F,2016-04-29T16:19:04Z,2016-04-29T00:00:00Z,62,MATA DA PRAIA,0,0,0,0,0,0,No
3,8.679512e+11,5642828,F,2016-04-29T17:29:31Z,2016-04-29T00:00:00Z,8,PONTAL DE CAMBURI,0,0,0,0,0,0,No
4,8.841186e+12,5642494,F,2016-04-29T16:07:23Z,2016-04-29T00:00:00Z,56,JARDIM DA PENHA,0,1,1,0,0,0,No
5,9.598513e+13,5626772,F,2016-04-27T08:36:51Z,2016-04-29T00:00:00Z,76,REPÃšBLICA,0,1,0,0,0,0,No
6,7.336882e+14,5630279,F,2016-04-27T15:05:12Z,2016-04-29T00:00:00Z,23,GOIABEIRAS,0,0,0,0,0,0,Yes
7,3.449833e+12,5630575,F,2016-04-27T15:39:58Z,2016-04-29T00:00:00Z,39,GOIABEIRAS,0,0,0,0,0,0,Yes
8,5.639473e+13,5638447,F,2016-04-29T08:02:16Z,2016-04-29T00:00:00Z,21,ANDORINHAS,0,0,0,0,0,0,No
9,7.812456e+13,5629123,F,2016-04-27T12:48:25Z,2016-04-29T00:00:00Z,19,CONQUISTA,0,0,0,0,0,0,No
10,7.345362e+14,5630213,F,2016-04-27T14:58:11Z,2016-04-29T00:00:00Z,30,NOVA PALESTINA,0,0,0,0,0,0,No
11,7.542951e+12,5620163,M,2016-04-26T08:44:12Z,2016-04-29T00:00:00Z,29,NOVA PALESTINA,0,0,0,0,0,1,Yes
12,5.666548e+14,5634718,F,2016-04-28T11:33:51Z,2016-04-29T00:00:00Z,22,NOVA PALESTINA,1,0,0,0,0,0,No
13,9.113946e+14,5636249,M,2016-04-28T14:52:07Z,2016-04-29T00:00:00Z,28,NOVA PALESTINA,0,0,0,0,0,0,No
14,9.988472e+13,5633951,F,2016-04-28T10:06:24Z,2016-04-29T00:00:00Z,54,NOVA PALESTINA,0,0,0,0,0,0,No
15,9.994839e+10,5620206,F,2016-04-26T08:47:27Z,2016-04-29T00:00:00Z,15,NOVA PALESTINA,0,0,0,0,0,1,No
16,8.457439e+13,5633121,M,2016-04-28T08:51:47Z,2016-04-29T00:00:00Z,50,NOVA PALESTINA,0,0,0,0,0,0,No
17,1.479497e+13,5633460,F,2016-04-28T09:28:57Z,2016-04-29T00:00:00Z,40,CONQUISTA,1,0,0,0,0,0,Yes
18,1.713538e+13,5621836,F,2016-04-26T10:54:18Z,2016-04-29T00:00:00Z,30,NOVA PALESTINA,1,0,0,0,0,1,No
19,7.223289e+12,5640433,F,2016-04-29T10:43:14Z,2016-04-29T00:00:00Z,46,DA PENHA,0,0,0,0,0,0,No
20,6.222575e+14,5626083,F,2016-04-27T07:51:14Z,2016-04-29T00:00:00Z,30,NOVA PALESTINA,0,0,0,0,0,0,Yes
21,1.215484e+13,5628338,F,2016-04-27T10:50:45Z,2016-04-29T00:00:00Z,4,CONQUISTA,0,0,0,0,0,0,Yes
22,8.632298e+14,5616091,M,2016-04-25T13:29:16Z,2016-04-29T00:00:00Z,13,CONQUISTA,0,0,0,0,0,1,Yes
23,2.137540e+14,5634142,F,2016-04-28T10:27:05Z,2016-04-29T00:00:00Z,46,CONQUISTA,0,0,0,0,0,0,No
24,8.734858e+12,5641780,F,2016-04-29T14:19:19Z,2016-04-29T00:00:00Z,65,TABUAZEIRO,0,0,0,0,0,0,No
25,5.819370e+12,5624020,M,2016-04-26T15:04:17Z,2016-04-29T00:00:00Z,46,CONQUISTA,0,1,0,0,0,1,No
26,2.578785e+10,5641781,F,2016-04-29T14:19:42Z,2016-04-29T00:00:00Z,45,BENTO FERREIRA,0,1,0,0,0,0,No
27,1.215484e+13,5628345,F,2016-04-27T10:51:45Z,2016-04-29T00:00:00Z,4,CONQUISTA,0,0,0,0,0,0,No
28,5.926172e+12,5642400,M,2016-04-29T15:48:02Z,2016-04-29T00:00:00Z,51,SÃƒO PEDRO,0,0,0,0,0,0,No
29,1.225776e+12,5642186,F,2016-04-29T15:16:29Z,2016-04-29T00:00:00Z,32,SANTA MARTHA,0,0,0,0,0,0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110497,7.935892e+14,5757745,M,2016-06-01T09:46:33Z,2016-06-01T00:00:00Z,76,MARIA ORTIZ,0,0,0,0,0,0,No
110498,9.433654e+13,5787655,F,2016-06-08T10:21:14Z,2016-06-08T00:00:00Z,59,MARIA ORTIZ,0,0,0,0,0,0,No
110499,8.219692e+14,5757697,F,2016-06-01T09:42:56Z,2016-06-01T00:00:00Z,66,MARIA ORTIZ,0,1,1,0,0,0,No
110500,4.434384e+14,5787233,F,2016-06-08T09:35:13Z,2016-06-08T00:00:00Z,59,MARIA ORTIZ,0,0,0,0,0,0,No
110501,4.544252e+11,5758133,M,2016-06-01T10:19:12Z,2016-06-01T00:00:00Z,44,MARIA ORTIZ,0,0,0,0,0,0,No
110502,7.316229e+14,5787937,F,2016-06-08T10:50:42Z,2016-06-08T00:00:00Z,22,GOIABEIRAS,0,0,0,0,0,0,No
110503,2.362182e+13,5759473,F,2016-06-01T13:00:36Z,2016-06-01T00:00:00Z,64,SOLON BORGES,0,0,0,0,0,0,No
110504,9.947983e+12,5788052,F,2016-06-08T11:06:21Z,2016-06-08T00:00:00Z,4,MARIA ORTIZ,0,0,0,0,0,0,No
110505,5.667344e+13,5758455,F,2016-06-01T10:45:50Z,2016-06-01T00:00:00Z,55,MARIA ORTIZ,0,0,0,0,0,0,No
110506,8.973883e+11,5758779,M,2016-06-01T11:09:20Z,2016-06-01T00:00:00Z,5,MARIA ORTIZ,0,0,0,0,0,0,No
110507,4.769462e+14,5786918,F,2016-06-08T09:04:18Z,2016-06-08T00:00:00Z,0,MARIA ORTIZ,0,0,0,0,0,0,No
110508,9.433654e+13,5757656,F,2016-06-01T09:41:00Z,2016-06-01T00:00:00Z,59,MARIA ORTIZ,0,0,0,0,0,0,No
110509,4.952968e+14,5786750,M,2016-06-08T08:50:51Z,2016-06-08T00:00:00Z,33,MARIA ORTIZ,0,0,0,0,0,0,No
110510,2.362182e+13,5757587,F,2016-06-01T09:35:48Z,2016-06-01T00:00:00Z,64,SOLON BORGES,0,0,0,0,0,0,No
110511,8.235996e+11,5786742,F,2016-06-08T08:50:20Z,2016-06-08T00:00:00Z,14,MARIA ORTIZ,0,0,0,0,0,0,No
110512,9.876246e+13,5786368,F,2016-06-08T08:20:01Z,2016-06-08T00:00:00Z,41,MARIA ORTIZ,0,0,0,0,0,0,No
110513,8.674778e+13,5785964,M,2016-06-08T07:52:55Z,2016-06-08T00:00:00Z,2,ANTÃ”NIO HONÃ“RIO,0,0,0,0,0,0,No
110514,2.695685e+12,5786567,F,2016-06-08T08:35:31Z,2016-06-08T00:00:00Z,58,MARIA ORTIZ,0,0,0,0,0,0,No
110515,6.456342e+14,5778621,M,2016-06-06T15:58:05Z,2016-06-08T00:00:00Z,33,MARIA ORTIZ,0,1,0,0,0,0,Yes
110516,6.923772e+13,5780205,F,2016-06-07T07:45:16Z,2016-06-08T00:00:00Z,37,MARIA ORTIZ,0,0,0,0,0,0,Yes
110517,5.574942e+12,5780122,F,2016-06-07T07:38:34Z,2016-06-07T00:00:00Z,19,MARIA ORTIZ,0,0,0,0,0,0,No
110518,7.263315e+13,5630375,F,2016-04-27T15:15:06Z,2016-06-07T00:00:00Z,50,MARIA ORTIZ,0,0,0,0,0,1,No
110519,6.542388e+13,5630447,F,2016-04-27T15:23:14Z,2016-06-07T00:00:00Z,22,MARIA ORTIZ,0,0,0,0,0,1,No
110520,9.969977e+14,5650534,F,2016-05-03T07:51:47Z,2016-06-07T00:00:00Z,42,MARIA ORTIZ,0,0,0,0,0,1,No
110521,3.635534e+13,5651072,F,2016-05-03T08:23:40Z,2016-06-07T00:00:00Z,53,MARIA ORTIZ,0,0,0,0,0,1,No
110522,2.572134e+12,5651768,F,2016-05-03T09:15:35Z,2016-06-07T00:00:00Z,56,MARIA ORTIZ,0,0,0,0,0,1,No
110523,3.596266e+12,5650093,F,2016-05-03T07:27:33Z,2016-06-07T00:00:00Z,51,MARIA ORTIZ,0,0,0,0,0,1,No
110524,1.557663e+13,5630692,F,2016-04-27T16:03:52Z,2016-06-07T00:00:00Z,21,MARIA ORTIZ,0,0,0,0,0,1,No
110525,9.213493e+13,5630323,F,2016-04-27T15:09:23Z,2016-06-07T00:00:00Z,38,MARIA ORTIZ,0,0,0,0,0,1,No
110526,3.775115e+14,5629448,F,2016-04-27T13:30:56Z,2016-06-07T00:00:00Z,54,MARIA ORTIZ,0,0,0,0,0,1,No

## Data cleanup

- Cleanup column names
- Remove records with erroneous entries (e.g., negative ages). Look at what people have done in Kaggle

In [ ]:
# do data cleanup here
clean_appt_df = appt_df.rename(columns={'PatientId': 'Patient_ID', 'AppointmentID': 'Appointment_ID', 'Gender': 'Gender',
                        'ScheduledDay' : 'Scheduled_Day', 'AppointmentDay' : 'Appointment_Day', 'Age': 'Age',
                        'Neighbourhood' : 'Neighborhood', 'Scholarship' : 'Scholarship',
                        'Hipertension' : 'Hypertension', 'Diabetes' : 'Diabetes', 'Alcoholism' : 'Alcoholism',
                        'Handcap' : 'Disability', 'SMS_received' : 'SMS_Received', 'No-show' : 'No-Show'})

clean_appt_df

# highly recommend that you rename dataset
# e.g., if you used appt_df = pd.read_csv(...) above
# first thing to do here is clean_appt_df = appt_df

## Test set creation

- Create a test set of 20k records
- Use stratified sampling on the `No-Show` variable to make sure class proportions are the same for train and test sets
- Save train and test sets as csv files in the `processed_data` directory

In [ ]:
PROCESSED_DATA_DIR = 'processed_data'

# create test set with stratified sampling here
# refer to the intro notebook posted in class calendar for example

## Exploratory Data Analysis

Plot the `No-show` variable against other variables. Remember from this point forward you are only using the training set created in the previous step

In [ ]:
# Make plots here!

## Data preprocessing

Create a scikit pipeline for preprocessing the data to prepare it for ML algorithms. At a minimum your pipeline should:

- Standardize numerical variables
- Transform categorical variables into numeric variables

Optionally, you can perform any other transformation you think is suitable. Again, refer to the intro notebook for an example of setting up a preprocessing pipeline.

In [ ]:
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.pipeline import Pipeline, FeatureUnion
from sklearn.preprocessing import StandardScaler, LabelBinarizer

# create pipeline here!

# show the first 5 rows of the transformed training set